Imports System.IO
Imports System.Xml
Imports System.Windows.Forms

''' <summary>
''' PT3toCdata Converter Tool
''' Copyright 2022 mvac7 (aka aorante) 
''' 
''' Vortex PT3 to C data Converter Tool for PT3 Player MSX SDCC Library (fR3eL Project) 
''' or other libraries (that use the same generated data format).
''' 
''' Vortex Tracker And Vortex PT3 Player are developed by Sergey Bulba.
'''
''' License:
''' This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
''' as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
''' 
''' This program is distributed in the hope that it will be useful, 
''' but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
''' See the GNU General Public License for more details.
''' 
''' You should have received a copy of the GNU General Public License along with this program.    
''' If not, see http://www.gnu.org/licenses/
''' 
''' </summary>
Public Class PT3toCdataWin

    Private _txtPath As String

    Private PT3_FileData As Byte()

    Private TrackerName As String

    Private SongName As String
    Private SongAuthor As String
    Private SongNoteTable As Integer


    Private PT3_Path As String

    Private isData As Boolean

    Public Sub New()

        ' Esta llamada es exigida por el diseñador.
        InitializeComponent()

        ' Agregue cualquier inicialización después de la llamada a InitializeComponent().


    End Sub

    Private Sub PT3toCdataWin_Load(sender As Object, e As EventArgs) Handles Me.Load

        'About()

        NewProject()

        ' draw gradient in window-form background
        'Dim gradientBG As New Bitmap(Me.Width, Me.Height)
        'Dim newBrush As New Drawing.Drawing2D.LinearGradientBrush(New PointF(0, 0), New PointF(0, gradientBG.Height), Color.Gainsboro, Color.SkyBlue)
        'Dim oneGraphic As Graphics = Graphics.FromImage(gradientBG)
        'oneGraphic.FillRectangle(newBrush, New RectangleF(0, 0, gradientBG.Width, gradientBG.Height))
        'Me.BackgroundImage = gradientBG

    End Sub



    Private Sub NewProject()
        SetTitle("")

        OutputToolsPanel.Enabled = False

        Me.PT3_Path = ""
        Me.TrackerName = ""
        Me.SongName = ""
        Me.SongAuthor = ""
        Me.SongNoteTable = 0

        ProjectNameTextBox.Text = ""

        Name_TextBox.Text = ""
        Author_TextBox.Text = ""
        NoteTableTextBox.Text = ""

        ShowHelptext()
    End Sub



    Private Sub SetTitle(ByVal filename As String)

        Dim debuging As String = ""

        If Not filename = "" Then
            filename = " · [" + filename + "]"
        End If

        'If Me.TEST_MODE Then
        '    debuging = " > DEBUG MODE <"
        'End If

        Me.Text = My.Application.Info.Title + " v" + My.Application.Info.Version.ToString + filename
    End Sub



    Private Sub ShowHelptext()
        OutputText.Text = "Welcome to " + My.Application.Info.ProductName + " v" + My.Application.Info.Version.ToString + vbNewLine
        OutputText.Text += Strings.StrDup(80, "-") + vbNewLine
        OutputText.Text += "How to:" + vbNewLine
        OutputText.Text += "1) Run Vortex Tracker, load a song and export to .PT3" + vbNewLine
        OutputText.Text += "2) Load a binary PT3 file." + vbNewLine
        OutputText.Text += "3) Configure output data." + vbNewLine
        OutputText.Text += "4) Save the source generated by the application." + vbNewLine
        OutputText.Text += "5) Include in your SDCC project" + vbNewLine
        OutputText.Text += vbTab + "#include " + Chr(34) + "SONG01_PT3.h" + Chr(34)
        isData = False
    End Sub



    ''' <summary>
    ''' Load binary file.
    ''' </summary>
    ''' <param name="filePath"></param>
    ''' <returns></returns>
    ''' <remarks></remarks>
    Private Function LoadBinary(ByVal filePath As String) As Byte()

        Dim aStream As FileStream
        Dim aFile As New FileInfo(filePath)

        Dim aFileData As Byte()

        Dim conta As Integer = 7

        Dim filesize As Long = aFile.Length - 1

        If filesize > 65536 Then
            Return Nothing
        End If

        aStream = New System.IO.FileStream(filePath, FileMode.Open)

        ReDim aFileData(filesize)

        aStream.Read(aFileData, 0, filesize)
        aStream.Close()

        Return aFileData

    End Function



    Private Sub InitFileData()

        Dim trackerNameASCII(21) As Byte
        Dim songNameASCII(31) As Byte
        Dim songAuthorASCII(31) As Byte

        Array.Copy(Me.PT3_FileData, 0, trackerNameASCII, 0, 22)
        Array.Copy(Me.PT3_FileData, 30, songNameASCII, 0, 32)
        Array.Copy(Me.PT3_FileData, 66, songAuthorASCII, 0, 32)

        Me.TrackerName = System.Text.Encoding.ASCII.GetString(trackerNameASCII)
        Me.SongName = System.Text.Encoding.ASCII.GetString(songNameASCII)
        Me.SongAuthor = System.Text.Encoding.ASCII.GetString(songAuthorASCII)

        Me.SongNoteTable = CInt(Me.PT3_FileData(99))

        Me.SongName = Me.SongName.Trim()
        Me.SongAuthor = Me.SongAuthor.Trim()

        Me.Name_TextBox.Text = Me.SongName
        Me.Author_TextBox.Text = Me.SongAuthor
        Me.NoteTableTextBox.Text = CStr(Me.SongNoteTable)

        ProjectNameTextBox.Text = Path.GetFileName(Me.PT3_Path)

        GenerateData()

        OutputToolsPanel.Enabled = True

    End Sub



    Private Sub GenerateData()

        Dim aDataFormat As New DataFormat

        Dim labelName As String = Me.LabelTextBox.Text

        Dim comments As New ArrayList

        Dim outputData() As Byte

        Dim fileOutputSize As Integer
        Dim initValue As Integer = 0


        If Me.PT3_FileData Is Nothing Then
            Exit Sub
        End If


        If Me.HeaderCheckBox.Checked Then
            initValue = 100
        End If

        fileOutputSize = (Me.PT3_FileData.Length - initValue)

        ReDim outputData(fileOutputSize - 1)

        Array.Copy(Me.PT3_FileData, initValue, outputData, 0, fileOutputSize)

        OutputText.Text = "// " + Me.TrackerName + vbNewLine
        OutputText.Text += "// Song name: " + Me.SongName + vbNewLine
        OutputText.Text += "// Song author: " + Me.SongAuthor + vbNewLine
        OutputText.Text += "// Note Table: " + CStr(Me.SongNoteTable) + vbNewLine + vbNewLine

        If SongInfo_CheckBox.Checked Then
            OutputText.Text += "const char " + labelName + "_name[] = " + Chr(34) + Me.SongName + Chr(34) + ";" + vbNewLine
            OutputText.Text += "const char " + labelName + "_author[] = " + Chr(34) + Me.SongAuthor + Chr(34) + ";" + vbNewLine + vbNewLine
        End If

        comments.Add(Path.GetFileName(Me.PT3_Path))
        comments.Add("Length: " + CStr(outputData.Length))
        If Me.HeaderCheckBox.Checked Then
            comments.Add("Not contain the 100 Byte header")
        End If

        OutputText.Text += aDataFormat.GetCcode(outputData, 16, DataFormat.DataType.HEXADECIMAL_0xnn, labelName, comments, "const char")

    End Sub


    ''' <summary>
    ''' Copy output to clipboard
    ''' </summary>
    ''' <remarks></remarks>
    Private Sub CopyAll()
        If Me.OutputText.Text = "" Then
            MsgBox("Nothing to copy", MsgBoxStyle.Exclamation, "Alert")
        Else
            My.Computer.Clipboard.SetText(Me.OutputText.Text)
        End If
    End Sub




    Private Sub Load_Dialog()
        'If Me.binaryFilePath = "" Then
        Me.OpenFileDialog1.FileName = ""
        '    Me.OpenFileDialog1.InitialDirectory = Me.AppConfig.PathItemBinary.Path
        'Else
        '    Me.OpenFileDialog1.FileName = Path.GetFileName(Me.filePath)
        '    Me.OpenFileDialog1.InitialDirectory = Path.GetDirectoryName(Me.filePath)
        'End If

        'Me.OpenFileDialog1.DefaultExt = "prj"
        Me.OpenFileDialog1.Filter = "Vortex Tracker files|*.pt3"

        If OpenFileDialog1.ShowDialog() = Windows.Forms.DialogResult.OK Then
            LoadPT3(OpenFileDialog1.FileName)
        End If

    End Sub


    Private Sub LoadPT3(ByVal filePath As String)

        Me.PT3_Path = filePath

        Me.PT3_FileData = LoadBinary(filePath)
        SetTitle(Path.GetFileName(filePath))

        InitFileData()

    End Sub




    Private Sub SaveSourceDialog()

        If Me.OutputText.Text = "" Then
            MsgBox("Nothing to save", MsgBoxStyle.Exclamation, "Alert")
        Else

            Me.SaveFileDialog1.Filter = "C Header file|*.h"

            If Not Me.PT3_Path = "" Then
                Me.SaveFileDialog1.InitialDirectory = Path.GetDirectoryName(Me.PT3_Path)
                Me.SaveFileDialog1.FileName = Path.GetFileNameWithoutExtension(Me.PT3_Path) + "_PT3"
            End If

            If SaveFileDialog1.ShowDialog() = DialogResult.OK Then

                Me.saveCode(SaveFileDialog1.FileName)

            End If

        End If

    End Sub



    ''' <summary>
    ''' Save source output.
    ''' </summary>
    ''' <param name="filePath"></param>
    ''' <remarks></remarks>
    Private Sub saveCode(ByVal filePath As String)
        Dim aStreamWriterFile As New System.IO.StreamWriter(filePath)
        aStreamWriterFile.WriteLine(Me.OutputText.Text)
        aStreamWriterFile.Close()
    End Sub



    Private Sub Load_Button_Click(sender As Object, e As EventArgs) Handles Load_Button.Click
        Load_Dialog()
    End Sub



    Private Sub HeaderCheckBox_CheckedChanged(sender As Object, e As EventArgs) Handles HeaderCheckBox.CheckedChanged
        GenerateData()
    End Sub



    Private Sub SongInfo_CheckBox_CheckedChanged(sender As Object, e As EventArgs) Handles SongInfo_CheckBox.CheckedChanged
        GenerateData()
    End Sub



    Private Sub LabelTextBox_TextChanged(sender As Object, e As EventArgs) Handles LabelTextBox.TextChanged
        GenerateData()
    End Sub



    Private Sub PT3toCdataWin_DragEnter(sender As Object, e As DragEventArgs) Handles MyBase.DragEnter
        If (e.Data.GetDataPresent(DataFormats.FileDrop)) Then
            e.Effect = DragDropEffects.Copy
        Else
            e.Effect = DragDropEffects.None
        End If
    End Sub



    Private Sub PT3toCdataWin_DragDrop(sender As Object, e As DragEventArgs) Handles MyBase.DragDrop
        Dim tmpstr() As String = e.Data.GetData("FileDrop", False)
        Dim filePath As String = tmpstr(0)

        Me.BringToFront()
        Me.Activate()

        If Path.GetExtension(filePath).ToUpper = ".PT3" Then
            LoadPT3(filePath)
        End If

    End Sub



    Private Sub About()

        Dim description As String

        Dim _about As New AboutWin()

        description = My.Application.Info.Description + vbNewLine + vbNewLine
        description += "Vortex Tracker and Vortex PT3 Player are developed by Sergey Bulba."

        _about.SetIcon = Global.mSXdevtools.PT3toCdata.My.Resources.Resources.PT3toC_icon01_128
        _about.SetLogo = Global.mSXdevtools.PT3toCdata.My.Resources.Resources.PT3toCdata_logo
        _about.SetDescription = description

        _about.ShowDialog(Me)

    End Sub



    Private Sub About_Button_Click(sender As Object, e As EventArgs) Handles About_Button.Click
        About()
    End Sub

    Private Sub CopyAllButton_Click(sender As Object, e As EventArgs) Handles CopyAllButton.Click
        CopyAll()
    End Sub

    Private Sub SaveSourceButton_Click(sender As Object, e As EventArgs) Handles SaveSourceButton.Click
        SaveSourceDialog()
    End Sub

    Private Sub NewButton_Click(sender As Object, e As EventArgs) Handles NewButton.Click
        NewProjectDialog()
    End Sub


    Private Sub NewProjectDialog()
        Dim MessageWin As New MessageDialog
        Dim result As DialogResult

        Beep()
        result = MessageWin.ShowDialog(Me, "New Project", "This option will erase all data." + vbCrLf + "Do you want to continue?", MessageDialog.DIALOG_TYPE.YES_NO) '+ vbCrLf

        If result = DialogResult.Yes Then
            'RemoveHandlers()
            NewProject()
            'AddHandlers()
        End If
    End Sub




End Class
